---
- hosts: centOS
  become: true

  vars:
    apache_package: httpd
    php_package: php

  tasks:
    - name: install apache (httpd) and php
      dnf:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"






